Question 2: Convolution Operations with Different Parameters.

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.models import Sequential

# Define the 5×5 input matrix
input_matrix = np.array([[1, 2, 3, 4, 5],
                         [5, 4, 3, 2, 1],
                         [6, 7, 8, 9, 0],
                         [0, 9, 8, 7, 6],
                         [1, 3, 5, 7, 9]], dtype=np.float32)

# Reshape input to match TensorFlow format (batch_size, height, width, channels)
input_matrix = input_matrix.reshape(1, 5, 5, 1)

# Define the 3×3 kernel
kernel = np.array([[1, 0, -1],
                   [1, 0, -1],
                   [1, 0, -1]], dtype=np.float32)

# Reshape kernel to match TensorFlow format (height, width, in_channels, out_channels)
kernel = kernel.reshape(3, 3, 1, 1)

# Function to perform convolution
def apply_convolution(input_matrix, kernel, stride, padding):
    model = Sequential([
        Conv2D(filters=1, kernel_size=(3, 3), strides=stride, padding=padding,
               kernel_initializer=tf.constant_initializer(kernel), use_bias=False, input_shape=(5, 5, 1))
    ])
    output = model.predict(input_matrix)
    return output.squeeze()  # Remove unnecessary dimensions

# Perform convolutions with different stride and padding parameters
output_valid_1 = apply_convolution(input_matrix, kernel, stride=1, padding='valid')
output_same_1 = apply_convolution(input_matrix, kernel, stride=1, padding='same')
output_valid_2 = apply_convolution(input_matrix, kernel, stride=2, padding='valid')
output_same_2 = apply_convolution(input_matrix, kernel, stride=2, padding='same')

# Print results
print("Output (Stride=1, Padding='VALID'):\n", output_valid_1)
print("\nOutput (Stride=1, Padding='SAME'):\n", output_same_1)
print("\nOutput (Stride=2, Padding='VALID'):\n", output_valid_2)
print("\nOutput (Stride=2, Padding='SAME'):\n", output_same_2)


/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 192ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
Output (Stride=1, Padding='VALID'):
 [[ -2.  -2.   8.]
 [ -8.   2.  12.]
 [-14.  -4.   6.]]

Output (Stride=1, Padding='SAME'):
 [[ -6.   0.   0.   0.   6.]
 [-13.  -2.  -2.   8.  15.]
 [-20.  -8.   2.  12.  18.]
 [-19. -14.  -4.   6.  23.]
 [-12. -12.  -2.  -2.  14.]]

Output (Stride=2, Padding='VALID'):
 [[ -2.   8.]
 [-14.   6.]]

Output (Stride=2, Padding='SAME'):
 [[ -6.   0.   6.]
 [-20.   2.  18.]
 [-12.  -2.  14.]]
